[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = ["index.lua"]

# Handle card click
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:click()'''
position = "after"
payload = '''
if HeyListen.on_shop_card_buy(self) then return end
'''
match_indent = true
overwrite = false

# Handle shop render
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''function G.UIDEF.shop()'''
position = "after"
payload = '''
HeyListen.reset_listening("shop_buy")
HeyListen.reset_listening("shop_reroll")
HeyListen.reset_listening("card_sell")
HeyListen.reset_listening("card_use")
'''
match_indent = true
overwrite = false

# Handle shop reroll
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.FUNCS.reroll_shop = function(e)'''
position = "after"
payload = '''
if HeyListen.on_shop_reroll(e) then return end
'''
match_indent = true
overwrite = false

# Handle blind select
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.FUNCS.select_blind = function(e)'''
position = "after"
payload = '''
if HeyListen.on_blind_select(e) then return end
HeyListen.reset_listening("blind_select")
HeyListen.reset_listening("hand_play")
HeyListen.reset_listening("card_sell")
HeyListen.reset_listening("card_use")
'''
match_indent = true
overwrite = false

# Handle go to menu
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.FUNCS.go_to_menu = function(e)'''
position = "after"
payload = '''
HeyListen.reset_listening()
HeyListen.reset_listening_per_ante()
'''
match_indent = true
overwrite = false

# Handle ante up
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''G.GAME.round_resets.boss_rerolled = false'''
position = "after"
payload = '''
HeyListen.reset_listening_per_ante()
'''
match_indent = true
overwrite = false

# Handle booster skip
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.FUNCS.skip_booster = function(e)'''
position = "after"
payload = '''
if HeyListen.on_booster_skip(e) then return end
HeyListen.reset_listening("booster_skip")
'''
match_indent = true
overwrite = false

# Handle playing hand
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''G.FUNCS.play_cards_from_highlighted = function(e)'''
position = "after"
payload = '''
if HeyListen.on_hand_play(e) then return end
'''
match_indent = true
overwrite = false

# Handle card sell
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.FUNCS.sell_card = function(e)'''
position = "after"
payload = '''
if HeyListen.on_card_sell(e, e.config.ref_table) then return end
'''
match_indent = true
overwrite = false

# Handle card use
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.FUNCS.use_card = function(e, mute, nosave)'''
position = "after"
payload = '''
if HeyListen.on_card_use(e, e.config.ref_table, mute, nosave) then return end
'''
match_indent = true
overwrite = false
